### ISSUE TITLE
Plase Help Me ...

### ISSUE THREAD

**Issue by aliriahy** [thrasher-corp/gocryptotrader#1209]
Can you guide me what should I do to display the data (like candle data) in opendex? And what is the best way?

**Comment by aliriahy** [comment]
When I receive the data (for example from Bitfinex), how should I display them on the trade page in  OpenDax?

**Comment by thrasher-** [comment]
You can get candles via each exchange's `GetHistoricCandles` or `GetHistoricCandlesExtended` wrapper func. You can also use an individuals exchange package to access their own internal candle methods bypassing the above. WRT OpenDax, not sure and you'd have to refer to their docs.
