### ISSUE TITLE
Bug in gateio_wrapper.go , it should be 'y'

### ISSUE THREAD

**Issue by aaabigfish** [thrasher-corp/gocryptotrader#1544]
https://github.com/thrasher-corp/gocryptotrader/blob/34ef09dad655a5db059eb44941a7eb9467f8f447/exchanges/gateio/gateio_wrapper.go#L1609C52-L1609C53

`side, err = order.StringToOrderSide(spotOrders[x].Orders[x].Side)`  
replace to  
`side, err = order.StringToOrderSide(spotOrders[x].Orders[y].Side)`

**Comment by shazbert** [comment]
@aaabigfish Nice spotting! Thanks for letting us know I will include a fix for this in #1532

**Comment by thrasher-** [comment]
PR 1532 has been merged, thanks for reporting this
