### ISSUE TITLE
Bybit websocket handleSubscription issue

### ISSUE THREAD

**Issue by Vlomzzz** [thrasher-corp/gocryptotrader#1674]
# New Issue

## Context

[bybit_websocket.go file line #180](https://github.com/thrasher-corp/gocryptotrader/blob/ac731ce283f126e0a4184d377599da30dfd27d9d/exchanges/bybit/bybit_websocket.go#L180C1-L180C52)

> interval, err := intervalToString(kline.FiveMin)

Interval is hardcoded to 5m instead of channelsToSubscribe[i].Interval.

**Comment by shazbert** [comment]
@Vlomzzz Nice catch, there is a update for websocket subscription handling incoming in #1601 which should handle that. If you have time, you could pull those changes to your local branch and test them out to verify, which will help us in merging it faster. Thanks for your input.

**Comment by shazbert** [comment]
Also if you want to check out #1672 which will have all assets and websocket trading available for use.

**Comment by Vlomzzz** [comment]
Not sure if it helps, but for Bybit I'm using linear websocket functionality that is not officially supported, I believe, and for this PR subscriptions are broken (not complaining just mentioning), but raised issue was fixed indeed.

**Comment by Vlomzzz** [comment]
Since we're discussing here mentioned PRs. Can I ask why default subscriptions for Bybit doesn't respect subscriptions configuration section and subscribes to disabled channels by default? Is this an expected behavior?

**Comment by shazbert** [comment]
> Since we're discussing here mentioned PRs. Can I ask why default subscriptions for Bybit doesn't respect subscriptions configuration section and subscribes to disabled channels by default? Is this an expected behavior?

That doesn't sound right; It should if it's spot only on #1601, as it's constrained to only spot asset at the moment. But on #1672 it doesn't have #1601 as a dependency so it will be the old hardcoded behaviour. I will make a note of this and have a good test when I can in a couple of days time. Thanks for looking over this stuff! Join our slack if you have any further questions and I will be happy to help.
