### ISSUE TITLE
stream/buffer: Fix intermittment TestUpdateByIDAndAction failure

### ISSUE THREAD

**Issue by thrasher-** [thrasher-corp/gocryptotrader#1706]
# New Issue

## Context

Seen: https://github.com/thrasher-corp/gocryptotrader/actions/runs/11734682422/job/32691128799?pr=1682#step:10:3012

**Comment by shazbert** [comment]
[Maybe potential fix](https://github.com/thrasher-corp/gocryptotrader/pull/1682)
