### ISSUE TITLE
OKx's websocket monitor cycle

### ISSUE THREAD

**Issue by dazi005** [thrasher-corp/gocryptotrader#1721]
# New Issue

## Context
When I updated the latest code, I found that OKx's websocket could not establish a connection

![image](https://github.com/user-attachments/assets/91d8565f-cbce-4718-95f6-ebbe577e438b)

**Comment by thrasher-** [comment]
Can you provide more context as to how you're initialising it, whether it attempts to connect and then fails etc.? You can set Verbose to true in the config for OKX to provide you with more info to help troubleshoot the issue.

**Comment by dazi005** [comment]
Firstly, I used the real apikey and secret from OKX for testing. Without updating Gareth Kirwan * 2024/11/12 10:15 Okx: Add subscription configuration (# 1605), the two files here are subscribed normally. However, after updating, it is not possible to start main.go Then I rolled back the updated two files to the previous version and ran main.go to subscribe normally That's the situation, thank you!

**Comment by thrasher-** [comment]
It sounds like that it's not subscribing to any channels since none have been configured/enabled. Could you please check your logs to see if that's the case? By default, the default subscription config for OKX should look as follows:

```
    "subscriptions": [
     {
      "enabled": true,
      "channel": "allTrades",
      "asset": "all"
     },
     {
      "enabled": true,
      "channel": "orderbook",
      "asset": "all"
     },
     {
      "enabled": true,
      "channel": "ticker",
      "asset": "all"
     },
     {
      "enabled": true,
      "channel": "myOrders",
      "asset": "all",
      "authenticated": true
     },
     {
      "enabled": true,
      "channel": "myAccount",
      "authenticated": true
     }
    ]
```
    
 Calling `SetDefaults` will set the subscriptions to the default list above. `Setup` will then setup the websocket via `ok.generateSubscriptions`. 
 
 Are you using GCT as a lib or via the default main/engine instance?

**Comment by dazi005** [comment]
The default main/engine instance ,I'll try to set it with gct to see if it works.

**Comment by dazi005** [comment]
<img width="904" alt="image" src="https://github.com/user-attachments/assets/b9d1845a-6a6d-45e0-b8a2-4b9d6741e0d3">
<img width="855" alt="image" src="https://github.com/user-attachments/assets/8a6f0433-4870-4e44-bcd5-790ae8492b18">

**Comment by thrasher-** [comment]
The area in particular is under each exchange's features. The subscriptions will automatically populate once you run GCT as follows:
![image](https://github.com/user-attachments/assets/a2462dd2-974d-4d7c-a369-52fb51a53339)

**Comment by dazi005** [comment]
When I put this configuration into config.josn, it works fine. Thank you very much,good....

**Comment by thrasher-** [comment]
Out of curiosity, did you use any additional parameters instead when running GCT? It's strange how your config wasn't upgraded automatically

**Comment by dazi005** [comment]
I now manually put the configuration into config.json. I am wondering where this gct command is called. Is it gctcli under cmd that is calling SetDefaults?

**Comment by dazi005** [comment]
"subscriptions": [
            {
              "enabled": true,
              "channel": "ticker"
            },
            {
              "enabled": true,
              "channel": "allTrades"
            },
            {
              "enabled": false,
              "channel": "candles",
              "interval": "15m"
            },
            {
              "enabled": false,
              "channel": "orderbook",
              "interval": "100ms"
            }
          ]
I configured it like this in config.json before, so it would report an error. Now I can remove this configuration and it will work.
