### ISSUE TITLE
exchanges/Bybit: Fix UpdateOrderExecutionLimits

### ISSUE THREAD

**Issue by thrasher-** [thrasher-corp/gocryptotrader#1729]
# New Issue

## Context

When running GCT, our logs are spammed by these events: Bybit unable to load limits for POPCATUSDT, pair data missing

**Comment by gloriousCode** [comment]
I believe I already worked on this on my own branch... But then accidentally refactored execution limits. I'll have a look to see if I can extract fixes. POPCATUSDT needs to be tradable at all times
