### ISSUE TITLE
Unique OrderID?

### ISSUE THREAD

**Issue by kempeng** [thrasher-corp/gocryptotrader#182]
I had a look at the code below in orders/orders.go: if OrderID is intented to be unique, and assigned by OrderID = len(Orders), would this not create orders with same ID's after an order is deleted from the Orders slice?

// Orders variable holds an array of pointers to order structs
var Orders []*Order

// Order struct holds order values
type Order struct {
	OrderID  int
	Exchange string
	Type     int
	Amount   decimal.Decimal
	Price    decimal.Decimal
}

// NewOrder creates a new order and returns a an orderID
func NewOrder(Exchange string, amount, price decimal.Decimal) int {
	order := &Order{}
	if len(Orders) == 0 {
		order.OrderID = 0
	} else {
		**order.OrderID = len(Orders)**
	}

	order.Exchange = Exchange
	order.Amount = amount
	order.Price = price
	Orders = append(Orders, order)
	return order.OrderID
}

// DeleteOrder deletes orders by ID and returns state
func DeleteOrder(orderID int) bool {
	for i := range Orders {
		if Orders[i].OrderID == orderID {
			**Orders = append(Orders[:i], Orders[i+1:]...)**
			return true
		}
	}
	return false
}

**Comment by shazbert** [comment]
@kempeng You are correct, this will need to be resolved.

**Comment by gloriousCode** [comment]
We do need a way of uniquely identifying each order, orderID shouldn't be that thing though as we get orderIDs back from exchanges. 

I agree that a uuid would be a good way to resolve it, but I think orders.go may be getting removed when the [engine branch](https://github.com/thrasher-/gocryptotrader/tree/engine) is merged

**Comment by kempeng** [comment]
take a lot at https://github.com/rs/xid, seems a bit more "lightweight"/shorter than a full uuid ...

**Comment by shazbert** [comment]
@kempeng Thanks for the suggestion! We will look into it.

**Comment by shazbert** [comment]
Internal UUID has been implemented in order_manager.go in `processSubmittedOrder`.
