### ISSUE TITLE
Coinbasepro submit order is broken

### ISSUE THREAD

**Issue by Christian-Achilli** [thrasher-corp/gocryptotrader#440]
# New Issue

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac

* GoCryptoTrader version (`gocryptotrader -version`): GoCryptoTrader v0.1 amd64 go1.13.6 pre-release.

## Expected Behavior

Is should open a limit order on my Coinbase pro account

## Current Behavior

It returns an error.

## Failure Information (for bugs)

Please help by providing information about the failure. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

To reproduce you need to use a real Trade enabled API key

Run this test:

func TestSubmitOrder(t *testing.T) {
	err := SubmitOrder("coinbasepro","BTC-EUR", "-", "BUY", "LIMIT", 1.0, 100.0 )
	if err != nil {
		t.Error(err)
	}
}

### Failure Logs
CoinbasePro unsuccessful HTTP status code: 400  raw response: {"message":"request timestamp expired"}

**Comment by Christian-Achilli** [comment]
I am trying to fix this right now

**Comment by gloriousCode** [comment]
Thanks for bringing this up!
In our `TestSubmitOrder`, its going through the wrapper. To fix this particular issue, in coinbasepro_wrapper.go function `SubmitOrder` you just need to replace `s.Side.String(),` to `s.Side.Lower(),`

**Comment by Christian-Achilli** [comment]
Hey, I tried that but I get another one now

"message":"request timestamp expired"

**Comment by Christian-Achilli** [comment]
Forget it it works :)
I am not sure why though. 
Using .Lower() it works fine.
I had tried with strings.ToLower() and I was getting the above!

**Comment by Christian-Achilli** [comment]
I have a similar issue when I try to cancel the order:

func TestCancelOrder(t *testing.T) {
	err := CancelOrder("coinbasepro", "2b2602c7-db69-40fe-86fa-e9d1fb6119b0")
	if err != nil {
		t.Error(err)
	}
}

rpc error: code = Unknown desc = CoinbasePro unsuccessful HTTP status code: 400  raw response: {"message":"request timestamp expired"}

**Comment by gloriousCode** [comment]
That's strange given that `Lower()` performs a `strings.ToLower()` Glad that you got it working!
When it comes to the "request timestamp expired", I'm not receiving that error. I think your computer time is out of sync with the server. See this: https://docs.pro.coinbase.com/#selecting-a-timestamp
Unfortunately, it does not look like coinbasepro has an endpoint where you can request their time to compare yours against.

**Comment by Christian-Achilli** [comment]
I found this https://api.pro.coinbase.com/time and here https://docs.pro.coinbase.com/#signing-a-message it says my clock should not be more than 30 secs apart from CB's.
My clock is practically aligned with CB's, still,  I randomly get that error, it seems. 
I'll do some more investigation

**Comment by Christian-Achilli** [comment]
I've enabled NTP client without improvement. 
It works (submits/cancel) an order from time to time, but mostly fails

**Comment by Christian-Achilli** [comment]
Using strconv.FormatInt(time.Now().Unix(), 10) instead of the nonce for CB-ACCESS-TIMESTAMP works fine. It's stable.

**Comment by gloriousCode** [comment]
Cool. If you want, you can open a PR, linking to this issue with all the fixes and we'll test to ensure that it works for us consistently as well before merging.
