### ISSUE TITLE
checkInsecureEndpoint logic seems backwards

### ISSUE THREAD

**Issue by azhang** [thrasher-corp/gocryptotrader#460]
https://github.com/thrasher-corp/gocryptotrader/blob/b686cf2e0e7e6b55f3bf62e381386e33effc9f86/exchanges/exchange.go#L634

Shouldn't it return if the endpoint *does* contain "https"

**Comment by thrasher-** [comment]
Fixed in https://github.com/thrasher-corp/gocryptotrader/pull/461
