### ISSUE TITLE
[Suggestion]: Discord + Github Projects

### ISSUE THREAD

**Issue by kifirkin** [thrasher-corp/gocryptotrader#494]
It would be awesome if you move from Slack to Discord and from Trello to Github Issues\Projects :)

**Comment by xtda** [comment]
Discord has two big limitations at the moment as its not really considered a "developer first platform"

It's ability to properly embed rich content it has basic support for slack style embeds but really needs to progress further

and its the integration with other CI toolchains

**Comment by thrasher-** [comment]
We have a few hundred members on the Slack service, plus have our CI services integrated with it and it would be an annoyance for everyone to shift over. At some point we will shift the project goals/milestones to GitHub but for now Trello does the job. 

Will close this for now but if any of these changes take place, I will report back.
