### ISSUE TITLE
exchConfig.CurrencyPairs.Pairs value incorrect

### ISSUE THREAD

**Issue by azhang** [thrasher-corp/gocryptotrader#528]
# New Issue

## Context

```
exchConfig, err := cfg.GetExchangeConfig("Bitmex")
log.Infof("%+v\n", exchConfig.CurrencyPairs.Pairs[asset.Futures])
log.Infof("%+v\n", exchConfig.CurrencyPairs.Pairs[asset.Perp])
```

My config excerpt:
```json
{
   "name": "Bitmex",
   "enabled": true,
   "verbose": true,
   "httpTimeout": 15000000000,
   "websocketResponseCheckTimeout": 30000000,
   "websocketResponseMaxLimit": 7000000000,
   "websocketTrafficTimeout": 30000000000,
   "websocketOrderbookBufferLimit": 5,
   "baseCurrencies": "USD",
   "currencyPairs": {
    "pairs": {
		 "futures": {
      "assetEnabled": null,
      "enabled": "",
      "available": "XRPZ19,BCHZ19,ADAZ19,EOSZ19,TRXZ19,XBTZ19,ETHZ19,LTCZ19",
      "requestFormat": {
       "uppercase": true
      },
      "configFormat": {
       "uppercase": true
      }
     },
     "perpetualcontract": {
      "assetEnabled": null,
      "enabled": "",
      "available": "XBTUSD,ETHUSD",
      "requestFormat": {
       "uppercase": true
      },
      "configFormat": {
       "uppercase": true
      }
     }
    }
   },
...
}
```

results in:
```
INFO[0000] &{AssetEnabled:0xc0002fc9a7 Enabled:[BCHZ19] Available:[XRPZ19 BCHZ19 ADAZ19 EOSZ19 TRXZ19 XBTZ19 ETHZ19 LTCZ19] RequestFormat:0xc0002a11c0 ConfigFormat:0xc0002a1200} 
INFO[0000] &{AssetEnabled:0xc0002fc9a8 Enabled:[ETHUSD] Available:[XBTUSD ETHUSD] RequestFormat:0xc0002a1280 ConfigFormat:0xc0002a12c0} 
```

Same occurs if I set `enabled` as `null`.

* Operating System: macos catalina

* GoCryptoTrader version (`gocryptotrader -version`): 
	github.com/thrasher-corp/gocryptotrader v0.0.0-20200724031809-14c72c9c6b45 // indirect
(14c72c9c6b45)

## Expected Behavior

Nothing should be enabled

## Current Behavior

element [1] in the list of Available pairs is Enabled if I put an empty or invalid pair in my Enabled config

## Failure Information (for bugs)

Please help by providing information about the failure. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

```
exchConfig, err := cfg.GetExchangeConfig("Bitmex")
log.Infof("%+v\n", exchConfig.CurrencyPairs.Pairs[asset.Futures])
log.Infof("%+v\n", exchConfig.CurrencyPairs.Pairs[asset.Perp])
```

### Failure Logs

By default and if file logging is enabled, GoCryptoTrader stores its `log.txt` file in `%APPDATA%\GoCryptoTrader\logs` on Windows and `~/.gocryptotrader/logs` on Linux/Unix/macOS. Raw text or a link to a pastebin type site is preferred.

**Comment by azhang** [comment]
So I found the code that does this, apparently intentionally. What is the reason for streaming a random pair? And if there's a typo, it should error rather than selecting a random pair

https://github.com/thrasher-corp/gocryptotrader/blob/14c72c9c6b45c7514917df29138f66602839ddf5/config/config.go#L506-L509

**Comment by thrasher-** [comment]
Since certain features require a pair to be enabled (ticker, orderbook, websocket subscription) we opted to have at least one pair enabled to ensure that this functionality is working as intended. This is assuming that a person loads up GCT with config_example values, which defaults to this behavior (at least one enabled pair/asset). Any toggling of an enabled pair which is either empty (assuming that the asset is enabled), or does not exist in the available pairs list, we'll reset it to a random pair. In the future we can make this more flexible but this is why it's done intentionally at the moment

**Comment by azhang** [comment]
Cool, makes sense to me. Thanks!

**Comment by thrasher-** [comment]
No worries!
