### ISSUE TITLE
FTX Reduce only order

### ISSUE THREAD

**Issue by romanornr** [thrasher-corp/gocryptotrader#585]
I might be totally wrong (only been using it for a few hours), and perhaps I can't find it, but not sure how I can make an order for FTX as a Reduce Only order.

```
	ordersubmission := order.Submit{
		Pair:          pair,
		Side:          order.Buy,
		Type:          order.Limit,
		Price:         newPrice,
		Amount:        0.01,
		AssetType:     asset.Futures,
		PostOnly: true,
		//ClientOrderID: "bot/Test"
	}
	
	submission, err := ftxManage.SubmitOrder(&ordersubmission)
	if err != nil {
		logrus.Warn(err)
	}
```

**Comment by shazbert** [comment]
You are totally correct. We don't have an order type for use in order.Submit struct and we don't translate it across to the function in ftx_wrapper.go:
![image](https://user-images.githubusercontent.com/9391715/97380417-19a53180-191b-11eb-8b25-78b3b96bf01a.png)

Thanks for letting us know, you can either wait for an update or you can open a PR yourself if you feel confident enough. Just confirm with us about what you want to do. 

Need any help you can contact me on Slack. [GoCryptoTrader Slack](https://join.slack.com/t/gocryptotrader/shared_invite/enQtNTQ5NDAxMjA2Mjc5LTc5ZDE1ZTNiOGM3ZGMyMmY1NTAxYWZhODE0MWM5N2JlZDk1NDU0YTViYzk4NTk3OTRiMDQzNGQ1YTc4YmRlMTk)

**Comment by thrasher-** [comment]
https://github.com/thrasher-corp/gocryptotrader/blob/master/exchanges/ftx/ftx_wrapper.go#L672 This is supported now!
