### ISSUE TITLE
Float as currency

### ISSUE THREAD

**Issue by jpillora** [thrasher-corp/gocryptotrader#589]
As a disclaimer, I haven't used this module, I was just reading the code. Though I was curious: Given https://stackoverflow.com/a/3730040/977939, whats the reasoning behind using `float64` to represent currency amounts?

**Comment by thrasher-** [comment]
We are using it for native convenience but definitely will be switching it over to a package with lossless precision (see open issue: https://github.com/thrasher-corp/gocryptotrader/issues/145)
