### ISSUE TITLE
Coinbene exchange not starting

### ISSUE THREAD

**Issue by aruokhai** [thrasher-corp/gocryptotrader#662]
# New Issue
Error when starting coinbene exchage
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
linux , ubuntu 16.0
* GoCryptoTrader version (`gocryptotrader -version`):
0..1
## Expected Behavior
to startup smoothly
## Current Behavior
error, during startup

## Failure Information (for bugs)
panic: runtime error: slice bounds out of range [:-1]

goroutine 228 [running]:
github.com/thrasher-corp/gocryptotrader/exchanges/coinbene.(*Coinbene).FetchTradablePairs(0xc00000cd20, 0x15421ab, 0xd, 0x100, 0x1536d94, 0x4, 0x0, 0x0)

Please help by providing information about the failure. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. go run main.go

.

**Comment by thrasher-** [comment]
This PR https://github.com/thrasher-corp/gocryptotrader/pull/663 should fix it and is currently undergoing review
