### ISSUE TITLE
I want to learn the GCT, Please share me a step by step document.

### ISSUE THREAD

**Issue by wade-liwei** [thrasher-corp/gocryptotrader#684]
I want to learn the GCT, Please share me a step by step document.

**Comment by wade-liwei** [comment]
Could you please share me how to trade for a exchange and a coin pair ?

**Comment by thrasher-** [comment]
General tutorial/usage enquiries are best discussed in our Slack. Have replied to you in there.

**Comment by wade-liwei** [comment]
got it,

thank you so much.
