### ISSUE TITLE
Exchanges have no idea of precision

### ISSUE THREAD

**Issue by ydm** [thrasher-corp/gocryptotrader#740]
On the client side (i.e. `exchange.IBotExchange.SubmitOrder()`) we fill float64s for price, amount, etc. Proper precision should be handled at exchange level as it is (1) exchange-dependent, (2) imprecise to round a float64 on the client side and expect the string representation to reflect that rounding precisely.

**Comment by thrasher-** [comment]
Duplicate of https://github.com/thrasher-corp/gocryptotrader/issues/740, will be tracked there
