### ISSUE TITLE
Introduce `IBotExchange.ServerTime() (time.Time, error)` and implement it for all exchanges

### ISSUE THREAD

**Issue by ydm** [thrasher-corp/gocryptotrader#763]
Exchanges that do not support such a functionality should return `common.ErrFunctionNotSupported`.

**Comment by ydm** [comment]
Assign that one to me please.

**Comment by shazbert** [comment]
Core implementation has been done in #938, specific implementations can be done via PRs when needed. Thanks for bringing this to our attention.
