### ISSUE TITLE
CLI, GUI or Webgui?

### ISSUE THREAD

**Issue by lulu-angry** [thrasher-corp/gocryptotrader#866]
# New Issue

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux

* GoCryptoTrader version (`gocryptotrader -version`): 1.17.15

Hello there i want to try Gocryptotrader but i don't understand how to use it.
i'l already compile it with the last stable version of go.
but when i run it, i have only full log in my console that it right ?
but i cant enter any command so i come here to ask you if a gui or webgui exist?

**Comment by gloriousCode** [comment]
While there is a web GUI under [the web folder](https://github.com/thrasher-corp/gocryptotrader/tree/master/web), I wouldn't advise its use.

I recommend to most people that the best way to interact with GoCryptoTrader is via our tool GCTCLI located [here](https://github.com/thrasher-corp/gocryptotrader/tree/master/cmd/gctcli). When you have GoCryptoTrader up and running, use the CLI to issue commands. It uses GRPC to send commands to GoCryptoTrader and will return the result

For a list of commands on how to interact with GoCrypoTrader, check it out [here](https://api.gocryptotrader.app/)
