### ISSUE TITLE
binance USDTMarginedFutures SubmitOrder Bug

### ISSUE THREAD

**Issue by idoall** [thrasher-corp/gocryptotrader#912]
# New Issue
When binance places an order now, it will uniformly use submitorder. When submitorder enters, it will be verified by s.validate().

binance the currency security u standard contract, if the market has a price field, it will prompt {"code": - 1106, "MSG": "parameter 'price' send when not required.}"

If there is no price field, it cannot be verified by s.validate()

**Comment by thrasher-** [comment]
Hey @idoall, what order type were you using? A limit order without a price set should only throw the validation error. `UFuturesNewOrder` will set a price however if it's != 0

**Comment by thrasher-** [comment]
Closed due to inactivity but please feel free to re-open to continue troubleshooting further

**Comment by idoall** [comment]
STOP_MARKET or TAKE_PROFIT_MARKET
